[package]
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2021"
name = "foxlib"
publish = false
version = "0.1.0"

[features]
default = []
hash = ["image", "img_hash"]
jobs = ["faktory", "serde_json", "chrono"]

[dependencies]
chrono = {version = "0.4", optional = true}
faktory = {version = "0.12", optional = true}
hyper = {version = "0.14", features = ["http1", "tcp", "server"]}
image = {version = "0.23", optional = true}
img_hash = {version = "3", optional = true}
lazy_static = "1"
opentelemetry = {version = "0.17", features = ["rt-tokio"]}
opentelemetry-otlp = "0.10"
prometheus = {version = "0.13", features = ["process"]}
serde_json = {version = "1", optional = true}
thiserror = "1"
tokio = {version = "1", features = ["rt"]}
tracing = "0.1"
tracing-opentelemetry = "0.17"
tracing-subscriber = {version = "0.3", features = ["env-filter", "json"]}
